### ISSUE TITLE
search sould create a roter link as router -> products?search="...."

### ISSUE THREAD

**Issue by AnirupPat** [virtuelabs-io/rapido-web#102]
Make sure the search is cleared of when we naviagate from home page by clicking a card

**Comment by sharansp** [comment]
search from search box -> home page
--
search by selecting hierarchy/related search
delete related search
search on top of related search
delete related search again
Add related search -> reload and search again
Add rating
remove rating
add rating -> reaload and test
Add price range search -> reload and search again
Add price
remove price
add price-> reaload and test again
Sort by
apply low to high on specific search
searchedText + relatedSearch + price + rating + sort
searchedText + relatedSearch
searchedText + price
searchedText + rating
searchedText + sortby
searchedText + price + rating
searchedText + relatedSearch + price + rating
