### ISSUE TITLE
Search - Show hierarchy

### ISSUE THREAD

**Issue by sharansp** [virtuelabs-io/rapido-web#47]
- Move show related Panel to the bottom
- Keep the panels expanded except "show related"
- Add Hierarchy Panel
[https://github.com/virtuelabs-io/rapido-build-cf/blob/master/assets/api-data/product-hierarchy.json](url)

**Comment by sharansp** [comment]
Take #48 as priority

**Comment by sharansp** [comment]
![image](https://user-images.githubusercontent.com/14273375/63150418-5fcae980-c024-11e9-991c-4fe277908637.png)

**Comment by AnirupPat** [comment]
This issue is fixed. so closing this issue..
