### ISSUE TITLE
New VPC and Order deployments

### ISSUE THREAD

**Issue by sharansp** [virtuelabs-io/rapido-web#53]
Move dev environment into new VPC and Order deployments

**Comment by reddy-s** [comment]
New VPC Created and tested if how it would work in private subnets.
VPC has 2 Private subnets and 2 Public ones.
All resources will be deployed in the private subnet and API gateway sitting over it
Here is the [commit](https://github.com/virtuelabs-io/rapido-build-cf/commit/3fcaae6eb8c144af368c8c2d33e2719d06f16399)

Also, analyzed the order of deployments. Will need to move all the resources into the private subnets soon
